name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi
        pip install -r requirements.txt 
    - name: Set up SSH key
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p /home/ec2-user/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > /home/ec2-user/.ssh/id_rsa
        chmod 600 /home/ec2-user/.ssh/id_rsa
        ssh-keyscan -H ec2-174-129-45-19.compute-1.amazonaws.com >> /home/ec2-user/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh -i /home/ec2-user/.ssh/id_rsa ec2-user@ec2-174-129-45-19.compute-1.amazonaws.com 'bash -s' << 'ENDSSH'
        # Commands to run on EC2 instance
        cd /Micoservice-Bookings
        git pull
        python3 app.py
        ENDSSH

        
